<a href="https://colab.research.google.com/github/hagisileo/PyTorch/blob/master/12_Numpy%EC%9D%98_array(%ED%95%99%EC%83%9D).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# 파이썬-배열(리스트)


## (리스트)  1차원 배열 만들기

* [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
색 = ['빨강','노랑','파랑']
L1 = [0,1,2,3,4,5,6,7,8,9] 
# 리스트 변환 함수  list()를 이용하여 [1,3,5,7,9] 
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [ ]:
# L1 리스트에 인덱스로 값을 확인

In [ ]:
# 리스트의 자료형 확인
print(type(L1), L1[0], type(L1[0]))

<class 'list'> 0 <class 'int'>


# Numpy 모듈

## 1차원 배열 만들기


###  array() - Numpy 모듈
* 다차원 배열을 처리하는 파이썬의 패키지 중 하나
* 외부 패키지인만큼 **import 명령어**를 통해 불러오는 것은 꼭 필요
    - **import numpy as np**
    - 패키지: Numpy  별명: np
    - 형식) np.array  
    

* reshape(m,n) :형태를 변경 (m*n 행렬)


In [ ]:
import numpy as np 
np.__version__

'1.21.6'

# 넘파이 배열 만들기
* np.array() : 배열 선언

In [ ]:
# 리스트
L1 = [0,1,2,3,4,5,6,7,8,9] 
#넘파이 배열
n1 = np.array([1,4,2,3,5] )

n1

array([1, 4, 2, 3, 5])

In [ ]:
#자료형 확인하기
print(type(L1), type(n1))
print(L1[4], n1[1])
print(type (L1[4]), type(n1[2]))

<class 'list'> <class 'numpy.ndarray'>
4 4
<class 'int'> <class 'numpy.int64'>


- range() 와 np.arange()

In [ ]:
# L1 에 0 ~ 20까지 짝수리스트 만들기
L1 = list(range(0,21,2))
print(L1, type(L1), type(L1[5]))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20] <class 'list'> <class 'int'>


In [ ]:
# a1 에 0 ~ 20까지 짝수 배열  만들기
# arange()함수
n1 = np.arange(0, 21, 2)
print(n1, type(n1), n1.dtype) # 배열에 있는 자료형으 같은 자료형이다. 

[ 0  2  4  6  8 10 12 14 16 18 20] <class 'numpy.ndarray'> int64


In [ ]:
# print() 함수로 출력하는 경우, 
#리스트와 구분하기 위해 원소 사이에 쉼표 없이 출력



- dtype : 배열의 자료형


In [ ]:
# 정수와 실수 배열  [3.14,  4, 1, 0.5] 
# 넘파이의 배열 만들기
nf = np.array([3.14,4,1,0.5,'가'])
 #인덱스[1]의 값 4의 자료형은?
print(nf.dtype, nf) # 리스트에서 더 큰 자료형으로 출력 int > float > str

<U32 ['3.14' '4' '1' '0.5' '가']


In [ ]:
# 자료형을 변경 -> 실수형으로 동일하게
nf_i =  np.array([1,2,3,4])
nf_f =  np.array([1.,2 ,3 ,4.])
nf_o =  np.array([1.,2.,3.,4.], dtype=object) # float64(자료형 변경 전 )
# dtype속성 을 이용하여 값의 자료형을 변경(dtype = object)
print(nf_i.dtype)
print(nf_f.dtype)
print(nf_o.dtype)

int64
float64
object


## 2 차원 배열 - list

In [ ]:
# 2 차원 배열 - list
L2 = [[1, 3, 4, 6], 
   [6, 2, 8, 5], 
   [9, 5, 7, 3]]

In [ ]:
# 한 행씩 리스트로 출력
for 행 in range(len(L2)):
    print(L2[행])

[1, 3, 4, 6]
[6, 2, 8, 5]
[9, 5, 7, 3]


In [ ]:
# 각 각의 값을 출력    
for 행 in range(len(L2)):
    for 열 in range(len(L2[행])):
        print(L2[행][열])

1
3
4
6
6
2
8
5
9
5
7
3


## 2 차원 배열 - numpy모듈

In [ ]:
import numpy as np
# 2 차원 배열 - numpy
# numpy의 random 모듈
r1  = np.random.random(5)
print(r1)

[0.2234109  0.21466076 0.58986046 0.83535337 0.99400104]


In [ ]:
#3행4열 의 배열 만들기 
#size를 (행, 열)순으로 정의
r2 = np.random.random((3,4))
print(r2)


[[0.10327038 0.59181932 0.57726449 0.42329527]
 [0.33842858 0.92469157 0.99271852 0.96195551]
 [0.27737789 0.05218273 0.66002975 0.73400542]]


- ndim : 차원 
- shape: 차원별로 몇개의 원소로 구성되었는지 관리하는 형상
- itemsize  : 원소 하나의 길이

In [ ]:
print(r1.ndim, r2.ndim)
print(r1.shape, r2.shape)
print(r1.itemsize, r2.itemsize)

1 2
(5,) (3, 4)
8 8


##  2차원배열로 수정
- .reshape(행,열)  수정

In [ ]:
# 1차원 배열 생성
# range 함수, arange()
# [1, 2, 3, 4, 5, 6, 7, 8, 9]
r3 = np.arange(1,10)
r3.ndim # 1, 1차원 배열

1

In [ ]:
# .reshape((3, 3))  
# 1차원행렬을 (3행 3열) 으로 수정
r4 = r3.reshape((3,3))

In [ ]:
#dtype : 배열의 자료형

#ndim : 차원 

#shape: 차원별로 몇개의 원소로 구성되었는지 관리하는 형상
r4.reshape
#itemsize  : 원소 하나의 길이


<function ndarray.reshape>

##  처리속도 비교

In [ ]:
# 1,000,000 개의 데이터가 있을때 처리 속도 비교

big_array = np.random.rand(1000000) # 1,000,000 개의 데이터 생성


In [ ]:
# sum() 함수로  # 1,000,000 개의 데이터의 합계 계산 처리속도
%timeit sum(big_array)  
#  1 ms = 1000 µs
# 

10 loops, best of 5: 87 ms per loop


In [ ]:
# Numpy 패키지의  함수중 sum()
%timeit np.sum(big_array)

1000 loops, best of 5: 375 µs per loop


# 넘파이(array)와 파이썬(list) 차이

In [ ]:
L1 = [10, 5, 3, 7, 1, 5]
L2 =  [1,2,3,4,5,6] 

L1 + L2
# L1 - L2
# L1 * L2
# L1 / L2

[10, 5, 3, 7, 1, 5, 1, 2, 3, 4, 5, 6]

In [ ]:
import numpy as np
 
arr1 = np.array([10, 5, 3, 7, 1, 5])
arr2 = np.array([1,2,3,4,5,6] )

In [ ]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[11  7  6 11  6 11]
[ 9  3  0  3 -4 -1]
[10 10  9 28  5 30]
[10.          2.5         1.          1.75        0.2         0.83333333]


# Numpy 
- array에서 숫자인덱스만 가능
- 모든 값이 같은 자료형

- DateFrame은 표 형식의 데이터를 담기위한 자료형으로 2차원 numpy array에 부가적인 기능이 추가된 것이다. 
    - (DataFrame이 numpy array를 기반으로 만들어져 있어서 pandas를 쓰려면 numpy가 먼저 설치되어 있어야한다.)